// <auto-generated />
using DietList.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DietList.Migrations
{
  [DbContext(typeof(DietListContext))]
  partial class DietListContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("Relational:MaxIdentifierLength", 64)
          .HasAnnotation("ProductVersion", "5.0.0");

      modelBuilder.Entity("DietList.Models.Diet", b =>
          {
            b.Property<int>("DietId")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            b.Property<string>("Description")
                      .HasColumnType("longtext CHARACTER SET utf8mb4");

            b.Property<string>("Name")
                      .HasColumnType("longtext CHARACTER SET utf8mb4");

            b.Property<string>("Restriction")
                      .HasColumnType("longtext CHARACTER SET utf8mb4");

            b.HasKey("DietId");

            b.ToTable("Diets");
          });
#pragma warning restore 612, 618
    }
  }
}
